#######################################
# OUTPUT CONFIGURATION
#######################################

# Ruta al archivo JSON donde se guardarán los resultados de Idealista
PATH_RESULTS: output/idealista_registros.json

# Ruta al archivo Excel con los resultados
GMAIL_EXCEL: output/idealista_registros.xlsx


#######################################
# EMAIL CONFIGURATION
#######################################

# Asunto del correo electrónico
GMAIL_SUBJECT: "Idealista: Nuevas casas en venta"

# Lista de destinatarios de los correos
# Escribe los correos entre corchetes y separados por comas
# Ejemplo: ["persona1@gmail.com", "persona2@gmail.com"]
GMAIL_DESTINATION: []

#######################################
# TRIGGERS
#######################################

# USAR MODELO
USE_MODEL: False